### ISSUE TITLE
Ignore a specific key or keys that contain functions

### ISSUE THREAD

**Issue by scoutbranding** [dobromir-hristov/tailwindcss-export-config#11]
For example, this config:

```
module.exports = {
  theme: {
    ...
    customForms: theme => ({
      default: {
        'input, textarea, multiselect, select': {
          borderColor: theme('colors.teal.400'),
          '&:focus': {
            borderColor: theme('colors.teal.400'),
          },
        },
      },
    }),
    ...
  }
}
```

Will generate this variable:

`$customForms: (default-input, textarea, multiselect, select: [object Object]);`

And this build error:

```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...select, select:": expected ")", was "[object Object]);"
        on line 34 of resources/assets/styles/config/tailwind.scss
        from line 5 of resources/assets/styles/config/external.scss
        from line 8 of /Users/***/site/web/app/themes/resources/assets/styles/editor.scss
>> fault-input, textarea, multiselect, select: [object Object]);

   ------------------------------------------^
```

**Comment by dobromir-hristov** [comment]
Oh, do you think just ignoring functions is enough? I am using a helper from tailwind that should resolve these, but I guess it doesnt fully do that.
Would there be any drawback of this ignore? Sorry to ask, but I no longer use Tailwind.

**Comment by scoutbranding** [comment]
Yeah, I think ignoring functions would do the trick. I can't imagine a scenario where functions would need to be converted into variables... at least within the context of this package.

**Comment by dobromir-hristov** [comment]
Hey. Sorry to reply so late, but I am trying to figure out what to do with this.

Tailwind allows you to reference values from the theme, but I think the example you gave, is nested allot more levels than what they suggest in the docs.

How would Tailwind resolve that setting into styles? 
How do you expect them to look in a sass/stylus vars? The resolved settings are just a nested object. It can probably try to return a nested map, with as close of a structure as possible? 

```json
{
  "default": {
    "input, textarea, multiselect, select": {
      "borderColor": "#4fd1c5",
      "&:focus": {
        "borderColor": "#4fd1c5"
      }
    }
  }
}
```

**Comment by joshuafredrickson** [comment]
No worries! 

The issue arose when we attempted to use this package in conjunction with the [@tailwindcss/custom-forms](https://tailwindcss-custom-forms.netlify.app/) plugin. In order to modify default styles, you need to use a `customForms` function in `theme` like displayed above.

In our use case, there's no need to access any values from `customForms` in scss, so skipping that key altogether work in this situation.

Alternatively, if it were to return a nested map, that would make the values accessible for others who may want full access to the entire nested list.

**Comment by dobromir-hristov** [comment]
I looked into this a bit more, this is potentially what a deep sass map may look like, in this situation. Frankly I dont see how someone might use it.

```scss
$customForms: (
  "default": (
    "input, textarea, multiselect, select": (
      "borderColor": #4fd1c5,
      "&:focus": (
        "borderColor": #4fd1c5
      )
    )
  )
);
```

Then again, its probably better, than just ignoring deeply nested maps..

**Comment by dobromir-hristov** [comment]
I pushed a potential fix for this in #16 
Could you take a look, see if this might help? It does not ignore functions, as they are actually resolved as objects by Tailwind, so it just deeply resolves them.

**Comment by joshuafredrickson** [comment]
Late to the party, but this is working great. Thanks!

**Comment by dobromir-hristov** [comment]
Which version did you end up using? With shallow or without?

**Comment by joshuafredrickson** [comment]
For this use case, we went with shallow.
