### ISSUE TITLE
Tailwind Breaking Change @ 1.6.0

### ISSUE THREAD

**Issue by kevcjones-archived** [dobromir-hristov/tailwindcss-export-config#19]
I've a got a build issue because of some new animation corePlugin vars that are not formed correctly.

```
$keyframes-spin-from-transform: rotate(0deg);
$keyframes-spin-to-transform: rotate(360deg);
$keyframes-ping-0%-transform: scale(1);
$keyframes-ping-0%-opacity: 1;
$keyframes-ping-75%, 100%-transform: scale(2);
$keyframes-ping-75%, 100%-opacity: 0;
$keyframes-pulse-0%, 100%-opacity: 1;
$keyframes-pulse-50%-opacity: .5;
$keyframes-bounce-0%, 100%-transform: translateY(-25%);
$keyframes-bounce-0%, 100%-animationTimingFunction: (cubic-bezier(0.8,0,1,1));
$keyframes-bounce-50%-transform: translateY(0);
$keyframes-bounce-50%-animationTimingFunction: (cubic-bezier(0,0,0.2,1));
```

I've tried to block the animation coreplugin but it doesn't see to be respecting the configuration, unless i've doing that wrong. 

Any immediate suggestions?

**Comment by dobromir-hristov** [comment]
I have not tried it yet, sorry. I need to see how the JavaScript object looks like before conversion

**Comment by kevcjones-archived** [comment]
No worries, I've forked for the moment - I think i can stick a custom package in place with 1.5.2 tailwindcss in it to prevent the issue. It's a temp solution.

**Comment by kevcjones-archived** [comment]
Not having much joy with that plan actually - i think i know why... I need to publish it so your build scripts work ... src level ain't gonna cut it :D - before i do this -  do you have a timeline for when you think you'll be able to look into?

**Comment by dobromir-hristov** [comment]
Try #20, should work for you. 1.6 broke allot of tests, so I cant finish it now, but this should fix your immediate problems.
