### ISSUE TITLE
just a litte info

### ISSUE THREAD

**Issue by dkern** [dobromir-hristov/tailwindcss-export-config#25]
Hi,

this is no issue, just wanted to let you know, that I like your work, and that I integrated it withing `Gulp`, where I use it like this. Maybe this would be nice for you to know.

https://www.npmjs.com/package/gulp-tailwindcss-export-config

Kind regards!

**Comment by dobromir-hristov** [comment]
Pretty awesome, make a PR to the readme, let's add it :)

**Comment by dkern** [comment]
Will do tomorrow!

**Comment by dkern** [comment]
I'll close this because it's done. ;)
Thank you!
