### ISSUE TITLE
Theme screens as variables not exported as SASS variables

### ISSUE THREAD

**Issue by kiril-daskalov** [dobromir-hristov/tailwindcss-export-config#28]
I have configured screens sizes but the they are not exported as SASS variables. I haven't checked for other preprocessors.
 
![image](https://user-images.githubusercontent.com/63586825/99193887-71012980-2784-11eb-92cb-439c08dee1f8.png)

**Comment by dobromir-hristov** [comment]
Could you please attach a minimal reproduction?

**Comment by kiril-daskalov** [comment]
Is this enough?


```
module.exports = {
  future: {},
  purge: [],
  theme: {
    extend: {
      fontSize: {
        base: [
          '1rem',
          {
            letterSpacing: '0.2px',
            lineHeight: '1.75rem',
          },
        ],
      },
    },
    colors: {
      white: 'hsl(0, 0%, 100%)',
    },
    screens: {
      sm: { min: '640px' },
      md: { min: '768px' },
      lg: { min: '1024px' },
      xl: { min: '1280px' },
    },
  },
  variants: {
    fluidContainer: ['responsive'],
    fontSize: ['responsive', 'hover', 'focus'],
  },
  corePlugins: {
    container: false,
  },
  plugins: [
    ({ addComponents, theme }) => {
      addComponents({
        '.container': {
          width: '100%',
          margin: '0 auto',
          padding: '0 20px',

          '@screen sm': {
            maxWidth: '654px',
          },
        },
      });
    },
  ],
};

```

**Comment by dobromir-hristov** [comment]
Alright cool, will debug a bit tomorrow. What version of tailwind are you using?

**Comment by kiril-daskalov** [comment]
> Alright cool, will debug a bit tomorrow. What version of tailwind are you using?

`1.9.6`

**Comment by dobromir-hristov** [comment]
OK so after some debugging, turns out the tailwind `resolveConfig` helper returns a `corePlugins` property without `screens,colors,spacing,keyframes`. This means we will always skip them. 

For the time being, you can specify `screens` in the `preserveKeys` property of this plugin, so you are sure they are kept after transformation. I think we should file a bug report on Tailwind repo.

**Comment by kiril-daskalov** [comment]
> OK so after some debugging, turns out the tailwind `resolveConfig` helper returns a `corePlugins` property without `screens,colors,spacing,keyframes`. This means we will always skip them.
> 
> For the time being, you can specify `screens` in the `preserveKeys` property of this plugin, so you are sure they are kept after transformation. I think we should file a bug report on Tailwind repo.

If you haven't already I will :)

**Comment by dobromir-hristov** [comment]
Filed the bug.

In the meantime just use preserveKeys on the extractor so your work is not blocked.

**Comment by kiril-daskalov** [comment]
ok, 10x
