### ISSUE TITLE
Omit suffix when detecting key 'default'

### ISSUE THREAD

**Issue by jordypereira** [dobromir-hristov/tailwindcss-export-config#3]
To keep the variables consistent with Tailwind, we might want to check if the key name is 'default' (or '') and omit the `-` if it is.
This could also be togglable with a variable.

Example: 

```
// rounded.js
  none: '0',
  default: '.25rem',
  full: '9999px',
```

Expected output: 

```
// rounded.less
@rounded-none: 0;
@rounded: .25rem;
@rounded-full: 9999px;
```

Actual output: 

```
// rounded.less
@rounded-none: 0;
@rounded-default: .25rem;
@rounded-full: 9999px;
```

**Comment by dobromir-hristov** [comment]
hmm good point. What would the proposed API look life, both for CLI and Node api ?

```bash
tailwindcss-export-config --config=tailwind.config.js --format=scss --ommit-defaults=true
```

```js
const converter = new TailwindExportConfig({
  config: 'path/to/tailwind.config.js',
  destination: 'converted/file/destination',
  format: 'scss',
  prefix: 'tw',
  flat: true,
  ommitDefaults: true
})
```

I think this should be off by default, but users can optionally turn it on, so vars are in sync with the tailwind classes.

**Comment by jordypereira** [comment]
I also think this should be off by default. So to disable it you need to put `--omit-defaults=false`

**Comment by dobromir-hristov** [comment]
If omitting is off by default, means we keep the format `padding-default` and only omit if we add the `omit-default:true` parameter.
Otherwise its a breaking change.

**Comment by jordypereira** [comment]
Should avoid breaking changes, you're right.

**Comment by dobromir-hristov** [comment]
So I implemented this, but what about nested maps? Sass Scss and Stylus all support nesting so this would not work. In tailwind, you would do tho like this `config('borderRadius.default')` 

https://tailwindcss.com/docs/functions-and-directives#config

I think in this case we should let this one go as it could introduce problems.

```scss
$borderRadius: (
  none: 0,
  sm: .125rem,
  default: .25rem,
  lg: .5rem,
  full: 9999px,
);"
```

**Comment by jordypereira** [comment]
What about only allowing it if `flat` is enabled?

Another use case:
Maybe we could at least omit the `-` when I provide an empty string? 
In my project I have already separated the variables I'm importing, 
and wrote a custom tailwind plugin that detects if it's `default` or `''` and then omits the `-`.

Would be nice if I could write my variables like this:
```js
rounded = {
  none: 0,
  sm: .125rem,
 '': .25rem,
  lg: .5rem,
  full: 9999px,
};
```

And not have a variable called `rounded-`

**Comment by dobromir-hristov** [comment]
I think that will cause a syntactic error in the compiler as the key will be empty when used with maps. I have to make this compatible with all variations, across preprocessors.
 `map_get($widths, '')` for sass for example.
The other thing is done, it will remove empty dashes.

**Comment by dobromir-hristov** [comment]
@perjor the 1.0.4 release now will automatically drop any names, that dont have a value, so in your case, rounded will be `$rounded` and `$rounded-lg` etc.
