### ISSUE TITLE
Feature request: Export config to JSON format

### ISSUE THREAD

**Issue by vitto** [dobromir-hristov/tailwindcss-export-config#50]
I really would use like this module to resolve my documentation problem illustrated here: https://github.com/tailwindlabs/tailwindcss/discussions/6301

This would be nice if I have my config in JSON format with all the values, also this would be nice as a base for Design Systems uses tailwind for the CSS part.

**Comment by dobromir-hristov** [comment]
Hey there. The tailwind api returns the options in a huge JS object. We iterate over them and create the variables.

Is there anything specific you want?

**Comment by vitto** [comment]
Thanks for the fast response, I would like to use the JSON config as a database to display contents in a very similar way of tailwind website (https://tailwindcss.com/docs/backdrop-blur).

I don't know how much is easy to do it, but it would be awesome to choose export only custom values or the whole config. This would ease me to display also differences between tailwind original and custom config by dumping both of them and make some kind of diff script.

As JSON format I think the module options you give are nice as they are, I don't know yet how we'll treat the data, but basically i expect something similar to that:

```json
{
  "blur": {
    "sm": "4px",
    ...
  },
  "backdropBlur": {
    "sm": "4px",
    ...
  },
}
```

or directly the final CSS value:

```json
{
  "blur": {
    "sm": "--tw-backdrop-blur: blur(4px);",
    ...
  },
  "backdropBlur": {
    "sm": "--tw-backdrop-blur: blur(4px);",
    ...
  },
}
```

or something more rich:

```json
{
  "blur": {
    "sm": {
      "css": "--tw-backdrop-blur: blur(4px);",
      "value": "4px",
    },
    ...
  },
  "backdropBlur": {
    "sm": {
      "css": "--tw-backdrop-blur: blur(4px);",
      "value": "4px",
    },
    ...
  },
}
```

I didn't used your module yet so I don't know how deep this is different from what you export right now, I hope this is not too hard to implement.

Just by the fact you'll add the possibility to export configs as JSON object you'll ease my work a lot.
I hope I've understood your question.

Thank you very much for your support!

**Comment by dobromir-hristov** [comment]
Something like this does the trick? https://gist.github.com/dobromir-hristov/e64057f44d2e29b956a6a5425c268d8f

**Comment by vitto** [comment]
Yes, it's exacly what I meant. It's perfect!
