### ISSUE TITLE
Malformed SCSS when using the 'flat' option

### ISSUE THREAD

**Issue by jtestarkey** [dobromir-hristov/tailwindcss-export-config#55]
When using the flat option with newer versions of tailwind, the scss is malformed, e.g.:

![image](https://user-images.githubusercontent.com/203510/151943212-916ab2e9-fac7-4703-a4c3-785ca1aa8794.png)

Is there any way to ignore the variables that have illegal characters?

**Comment by dobromir-hristov** [comment]
We could just add escaping for the full stop? `$height-2\.5: 2rem`

**Comment by jtestarkey** [comment]
Yeah that would be better!

**Comment by jtestarkey** [comment]
Hey @dobromir-hristov is this something you would be able to look at, or can you point me in the right direction and I'll have a look at it myself? Thanks!

**Comment by dobromir-hristov** [comment]
Extremely busy with my day job, so I have not had time to look into this.

There is a sanitizer function on each class, so I guess it's a matter of just doing some simple string replacement.

Which version of the library are you using?

**Comment by jtestarkey** [comment]
Not a problem, I understand. Currently using a old version of both this package and tailwind, but trying to upgrade both to latest.

**Comment by dobromir-hristov** [comment]
New versions have some extra fixes, so this may be fixed already

**Comment by jtestarkey** [comment]
Sorry, it currently 'works' in the older version but that's because that version of tailwind doesn't have the `0.5` variables.
Latest versions of both currently doesn't work due to those variable names.

**Comment by mjcbsn22** [comment]
+1

Tried updating to either 3.x or 4.x today and ran into the same issue

Reason for the upgrade urgency is because v2.3.1 depends on `postcss@6.0.23` through `tailwindcss -> postcss-functions`
