### ISSUE TITLE
Deprecation Using / for division is deprecated

### ISSUE THREAD

**Issue by stereonom** [dobromir-hristov/tailwindcss-export-config#59]
Hi.

I have the problem that my config generates something like this:

```
$tw-aspectRatio-video: 16 / 9;
````

And my sass is telling me, that `Using / for division is deprecated`

I googled a bit and found this quote:
> You need to define the aspect ratio as a string, otherwise Sass will compile the expression as a mathematical operation.

Can you add this feature?
This also applies to `$tw-gridColumn-span-1: span 1 / span 1;` 

---
In my case I don't need these variables in my scss. It would be fine for me to have an option to export only selected key. I just want screen, colors and spacing to be exported

**Comment by dobromir-hristov** [comment]
I think you can specify which ones to include. That should work for you
 Check the docs.

**Comment by stereonom** [comment]
I don't find the option to do this.

This is my script.
```
tailwindcss-export-config --config=tailwind.config.js --destination=dev/scss/misc/_tailwind --format=scss --flat=true --prefix=tw --preserveKeys=screens,spacing,colors
```

Only when I add `corePlugins: []` in my tailwind config, it includes *only* screens,spacing,colors.
But than my tailwind doesn't do anything. I can't use `gap` for example. But I want to use the tailwind gap classes. I just don't need the variables in my exported config.

**Comment by stereonom** [comment]
What I need is an option like
```
--onlyIncludeKeys=screens,spacing,colors
```

**Comment by stereonom** [comment]
I made a PR https://github.com/dobromir-hristov/tailwindcss-export-config/pull/60 :-)

**Comment by dobromir-hristov** [comment]
Merged!

**Comment by dobromir-hristov** [comment]
Released.
