### ISSUE TITLE
Preparation for Tailwind version 1

### ISSUE THREAD

**Issue by ingvoo** [dobromir-hristov/tailwindcss-export-config#6]
Nice work!

Just a head up. Tailwind is working on releasing version 1 and the structure of the `tailwind.config.js` has changed. I just tried this out with [Tailwind Beta 4](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0-beta.4) my outcome looks more or less like this (outputting scss):

```
$theme-colors: [object Object];
$theme-spacing: [object Object];
$theme-screens: [object Object];
$theme-fontFamily: [object Object];
$theme-fontSize: [object Object];
```

**Comment by dobromir-hristov** [comment]
Yeah, they are using objects now, which were not there before, from what I recall. I will try to do the fixes these days :)

**Comment by dobromir-hristov** [comment]
I am halfway there. Basic parsing is done, mostly cleaning up now.

**Comment by dobromir-hristov** [comment]
https://github.com/dobromir-hristov/tailwindcss-export-config/tree/fix/tailwind_v1 branch is pushed. Will release a beta version on NPM soon to test it out.

**Comment by tanc** [comment]
I'm finding this hard to work out how to use. Currently `main` in `package.json` points to a non-existent `dist/index.js` so `require` doesn't work. Running `yarn install` then `yarn build` throws errors.

Changing `dist/index.js` to `src/index.js` and then using it in webpack results in `SyntaxError: Unexpected identifier` in `(function (exports, require, module, __filename, __dirname) { import fse from 'fs-extra'`

Running it as a script results in an error:

`Error: Cannot find module './dist'`

Any pointers?

**Comment by ingvoo** [comment]
Hi @tanc, is your issue in anyway relevant to issue that I created (when using tailwind 1 beta 4)?

**Comment by dobromir-hristov** [comment]
Guys sorry, or was very late last night. I will fix it today and release a build :)

**Comment by dobromir-hristov** [comment]
OK lets try again :D use the `next` npm tag 

```bash
npm install tailwindcss-export-config@next
# or
yarn add tailwindcss-export-config@next
```

**Comment by ingvoo** [comment]
Thanks a lot @dobromir-hristov 
I just tried it out using npm script and it worked very well.

```
"export-tailwind": "tailwindcss-export-config --config=tailwind.config.js --destination=src/assets/scss/tailwind-configs --format=scss --flat=true --prefix=tw"
```

Closing this issue.
