### ISSUE TITLE
corePlugins still exported

### ISSUE THREAD

**Issue by ZebTheWizard** [dobromir-hristov/tailwindcss-export-config#8]
In tailwind, you can specify which utilities should be generated by listing them in an array. However, when I run your library, all the default tailwind values such as width and padding are still exported. I'm trying to just get variables for the colors.

Here is my config file:
```
    {
      prefix: '',
      important: false,
      separator: '',
      theme: {
        backgroundColor: {...},
        borderColor:{...},
        textColor:{...},
      },
      variants: [],
      corePlugins: ['backgroundColor', 'borderColor', 'textColor'],
      plugins: [],
    }
```

**Comment by dobromir-hristov** [comment]
Hey there. This is probably just how Tailwind resolves the config at the end. We are using their own provided helper for this.
Apart from generating more noise in your variable file, is there any other issue that you see?

**Comment by ZebTheWizard** [comment]
no, it just generates extra variables that I didn't really want.

**Comment by dobromir-hristov** [comment]
Hey @ZebTheWizard sorry for such a late reply 🤦 

I just pushed a PR #15 , which should fix this. LMK if that works for you and I will merge and release soon.

**Comment by nlemoine** [comment]
Hi @dobromir-hristov 

I just starting to work again on a project using your great package but noticed some variables disappeared from my exported Tailwind config after updating. 

The new feature introduced in this issue had an undesirable side effect on keys that don't depend on plugin settings, for instance, it removes `colors` and `screens` keys which are pretty important to anyone using this I guess.

Maybe some keys should be whitelisted?

**Comment by dobromir-hristov** [comment]
So you don't want the colors plugin, but still need the vars?

**Comment by nlemoine** [comment]
I may be wrong but I think keys such as `colors` or `screens` aren't plugins (https://tailwindcss.com/docs/configuration#core-plugins). They are used by plugins (`backgroundColor`, `borderColor`, etc.).

Yes, I need those vars in my scss file.

**Comment by dobromir-hristov** [comment]
You are right. Please create a new issue with the proposed solution, so we can track a fix easily.

How should that whitelist be defined or passed?
